### ISSUE TITLE
Add Vanguard

### ISSUE THREAD

**Issue by berlonce** [MiSTer-devel/Arcade-Phoenix_MiSTer#16]
I'd like to add Vanguard as a supported ROM. I understand that the HW is basically the same, so I expect only a new MRA is needed? @sorgelig any guidance you can provide would be much appreciated.

**Comment by sorgelig** [comment]
Rough guidance: take MAME rom description where you see number of roms and their addresses. So get description of already supported rom and the rom you want to add. Look at MRA and do a matching with supported rom and the one you want to add.

**Comment by berlonce** [comment]
Thanks. I'd made the mra (see below) and it produced the image linked below. I also messed with the vhd to add more button inputs that Vanguard requires. The rbf still works for Phoenix, but input isn't working right and I definitely don't know what I'm doing. Would love to have a mentor to help me work through the issues. I assume I need to make some if statements for different ROM cases to handle different inputs and memory maps, but that feels like bad form.

![image](https://user-images.githubusercontent.com/274078/162608577-5ece8c3e-f295-48bb-98e2-85a26133ef72.jpeg)

<misterromdescription>
	<name>Vanguard</name>
	<region></region>
	<homebrew>no</homebrew>
	<bootleg>no</bootleg>
	<version>SNK</version>
	<alternative></alternative>
	<platform></platform>
	<series></series>
	<year>1981</year>
	<manufacturer>SNK</manufacturer>
	<category>Shooter</category>

	<setname>vanguard</setname>
	<mameversion>0242</mameversion>
	<rbf>phoenix</rbf>
	<about></about>

	<resolution>15kHz</resolution>
	<rotation>vertical (cw)</rotation>
	<flip>yes</flip>

    <players>2 (alternating)</players>
	<joystick>8-way</joystick>
	<special_controls></special_controls>
	<num_buttons>4</num_buttons>
	<button_names></button_names>

	<rom index="1"></rom>
    <rom index="0" md5="none" zip="vanguard.zip">
		<part crc="6a29e354" name="sk4_ic07.bin"></part>
		<part crc="302bba54" name="sk4_ic08.bin"></part>
		<part crc="424755f6" name="sk4_ic09.bin"></part>
		<part crc="54603274" name="sk4_ic10.bin"></part>
		<part crc="fde157d0" name="sk4_ic13.bin"></part>
		<part crc="0d5b47d0" name="sk4_ic14.bin"></part>
		<part crc="8549b8f8" name="sk4_ic15.bin"></part>
		<part crc="062e0be2" name="sk4_ic16.bin"></part>
		<part crc="e7d4315b" name="sk5_ic50.bin"></part>
		<part crc="96e87858" name="sk5_ic51.bin"></part>
        	            <part crc="ad782a73" name="sk5_ic7.bin"></part>
                        <part crc="7dc9d450" name="sk5_ic6.bin"></part>
		<part crc="d2a64006" name="sk4_ic51.bin"></part>
		<part crc="cc4a0b6f" name="sk4_ic52.bin"></part>
                        <part crc="2b7cbae9" name="sk6_ic07.bin"></part>
                        <part crc="3b7e9d7c" name="sk6_ic08.bin"></part>
                        <part crc="c36df041" name="sk6_ic11.bin"></part>
		</rom>
	<rom index="2"></rom>
	<rom index="3" md5="none">
		<part>
		 00 00 00 00 00 FF 00 02 00 02 00 01 00 FF 00 00
		 00 00 43 89 00 03 00 00 
		 00 00 41 E1 00 01 20 20 
		 00 00 41 C1 00 01 20 20 
		 00 00 41 A1 00 01 20 20 
		 00 00 41 81 00 01 20 20 
		 00 00 41 61 00 01 20 20 
		 00 00 41 41 00 01 20 20 
		 00 00 43 81 00 03 00 00 
		 00 00 43 01 00 01 20 20 
		 00 00 42 E1 00 01 20 20 
		 00 00 42 C1 00 01 20 20 
		 00 00 42 A1 00 01 20 20 
		 00 00 42 81 00 01 20 20 
		 00 00 42 61 00 01 20 20 
		 00 00 43 85 00 03 00 00 
		 00 00 40 C1 00 01 20 20 
		 00 00 40 A1 00 01 20 20 
		 00 00 40 81 00 01 20 20 
		 00 00 40 61 00 01 20 20 
		 00 00 40 41 00 01 20 20 
		 00 00 40 21 00 01 20 20 
		</part>
		</rom>
	<rom index="4"></rom>

	<nvram index="4" size="27"></nvram>

	<remark></remark>

	<mratimestamp>20220406000000</mratimestamp>
</misterromdescription>

**Comment by JimmyStones** [comment]
@jgildred are you on Discord?  Happy to chat and work through the issues with you.

**Comment by berlonce** [comment]
Sounds good. Thanks!

**Comment by JimmyStones** [comment]
> Sounds good. Thanks!

Cool, you can find me as JimmyStones on the official MiSTer Discord here: https://discord.gg/SvEAbZRt

**Comment by berlonce** [comment]
This will likely need to be a new core.
