### ISSUE TITLE
rbf not found with Pleiads (Centuri).mra and Pleiads (Tehkan).mra

### ISSUE THREAD

**Issue by NML32** [MiSTer-devel/Arcade-Phoenix_MiSTer#9]
Pleidas won't load with the following mra files. Pleiads (Centuri).mra and Pleiads (Tehkan).mra I was getting an error rbf not found.
I removed Arcade- from <rbf>Arcade-Phoenix</rbf> then both started working.

**Comment by sorgelig** [comment]
fixed

**Comment by NML32** [comment]
Thank you.
